### ISSUE TITLE
Emoji breaks vertical table alignment

### ISSUE THREAD

**Issue by ghost** [jedib0t/go-pretty#202] opened 2022-04-20 04:55 UTC
**Describe the bug**
table elements with emojis in string break vertical alignment of the table, any fixes?
![send](https://user-images.githubusercontent.com/77295140/164156739-0ca60943-5036-424f-baef-5c44c566d5c8.png)

**To Reproduce**
https://goplay.tools/snippet/Un3XOwHqkiA

**Expected behavior**
vertical table alignment should not break

**Software (please complete the following information):**
 - OS: Linux:Ubuntu 20.04 LTS
 - GoLang Version 1.18.1

**Comment by jedib0t** [comment] 2022-04-20 15:54
Duplicate of https://github.com/jedib0t/go-pretty/issues/186 -- Aligning Unicode characters does not work 100% of the time. The typeface/font you use in your terminal, the terminal emulator you use, all play a role in how the emoji get rendered, and this is kinda impossible at this time to fix. I'm using the best library there is to compute the real-width of the emoji characters, but due to the above reasons, it may not work all the time.

I'd recommend keeping emoji out of aligned tables for now. :(

**Closed as completed** 2022-04-20 16:23 UTC
