### ISSUE TITLE
Text width issue for emoji with more than one code point

### ISSUE THREAD

**Issue by jalock** [jedib0t/go-pretty#105] opened 2020-05-09 14:01 UTC
![Demo](https://user-images.githubusercontent.com/60474369/81475686-55025580-9240-11ea-9b97-c2e51eab7601.png)

Check No.2 row in the snapshot above, the code points of [⚔️](https://emojipedia.org/crossed-swords/) is `U+2694 U+FE0F`, thus it's treated as two chars and made column broken.

Can you please fix this? Or got ideas to avoid this?

**Comment by jalock** [comment] 2020-05-09 14:03
Here's the code snippet:

```go
func renderTableContent() {
	date := time.Now()

	t := table.NewWriter()
	t.SetOutputMirror(os.Stdout)
	//t.SetStyle(table.StyleColoredBright)

	t.AppendHeader(table.Row{"#", "Key", "Value"})
	t.AppendRows([]table.Row{
		{1, "Emoji 1 🥰", date.UnixNano()},
		{2, "Emoji 2 ⚔️", date.UnixNano()},
		{3, "Emoji 3 🎁", date.UnixNano()},
	})
	t.AppendFooter(table.Row{"", "", "Total"})

	t.Render()
}
```

**Comment by jedib0t** [comment] 2020-05-09 14:06
Hey @jalock ... this is a potential duplicate of #78  and may not be easy to fix. Lemme take a deeper look today to see if I can do something about this.

**Comment by jedib0t** [comment] 2020-05-09 15:44
Hey... an update. I used the following code for the test-run:

```golang
func demoTableEmoji() {
	tw := table.NewWriter()
	tw.AppendHeader(table.Row{"Key", "Value"})
	tw.AppendRows([]table.Row{
		{"Emoji 1 🥰", 1000},
		{"Emoji 2 ⚔️", 2000},
		{"Emoji 3 🎁", 3000},
	})
	tw.AppendFooter(table.Row{"Total", 6000})
	tw.SetAutoIndex(true)
	//tw.SetStyle(table.StyleColoredBright)

	fmt.Println("\n" + tw.Render() + "\n")
}
```

In Microsoft Terminal (running WSL) with `Ubuntu for Powerline` typeface without any code-changes:

![table-emoji-before](https://user-images.githubusercontent.com/38574447/81478217-be4a8000-91d0-11ea-85de-a1ff0c57d362.png)
![table-emoji-before-simple](https://user-images.githubusercontent.com/38574447/81478218-c3a7ca80-91d0-11ea-8a85-46789ec6ae6b.png)


After updating to the latest version of `go-runewidth` library used by go-pretty:

![table-emoji-after-simple](https://user-images.githubusercontent.com/38574447/81478252-e508b680-91d0-11ea-8405-9bf509b3e556.png)
![table-emoji-after](https://user-images.githubusercontent.com/38574447/81478253-e639e380-91d0-11ea-8f58-4c893d419a93.png)


I'll send a PR for the dependency update, but I think that this may be out of the code's control and mode in the domain of the font/typeface used, and the terminal that finally renders it. If you find anything more about this, I'm open to hear about it, but I'm afraid this is all I can do for now. I'll keep an eye out for new developments on the same to see if I can deliver a fix.

**Comment by jalock** [comment] 2020-05-09 16:05
Thanks for your help and tips about `tw.SetAutoIndex(true)`!

My devenv is:
* os: macOS Catalina 10.15.4
* terminal: iTerm2
* font: CascadiaCode 12
* w/o Powerline

**Comment by jedib0t** [comment] 2020-05-09 16:10
@jalock Take a look at https://github.com/jedib0t/go-pretty/pull/106 -- I'm updating the underlying `go-runewidth` library that I use to calculate the real width of a Unicode string. This __may__ fix the issue for you -- but I'm not too sure.

I'll leave this bug open so that anyone else with knowledge on fixing this can chime in.

**Comment by jedib0t** [comment] 2020-05-09 17:28
@jalock Can you try cloning this repo and run `go run ./cmd/demo-table/demo.go emoji` and paste a screenshot?

**Comment by jalock** [comment] 2020-05-10 03:02
![go snap](https://user-images.githubusercontent.com/60474369/81489872-806f5980-92ad-11ea-8b08-7357e228879e.png)

Thanks for your efforts! Seems that #78 got fixed, whereas #105 haven't.

**Comment by jedib0t** [comment] 2020-05-11 21:11
@jalock Comparing our screenshots makes be believe more firmly that it is more of a system/application/font issue than something in this library.

In my screenshot from `Windows/Terminal/UbuntuMono for Powerline`, row #1 has an issue. In your screenshot from `Mac/iTerm2/CascadiaCode`, row #2 has an issue.

I'll try a few more typefaces/fonts and report.

**Comment by jedib0t** [comment] 2020-05-16 20:03
I tried on Microsoft Terminal with `Cascadia Code` with and without powerline, and I see a similar but different issue on Emoji 2: 
![image](https://user-images.githubusercontent.com/38574447/82129123-5ae2c400-9775-11ea-85c7-614d4d166568.png)

I'm guessing this is something to do with the actual typeface/font and may never be 100% solvable from the perspective of go-pretty. This is almost like trying to get non-monospaced characters into a monospaced table.

I'll leave this bug open though.

**Comment by jedib0t** [comment] 2020-05-19 20:42
Hey, here is a screenshot with release 1.0 of Microsoft Terminal ([from here](https://github.com/microsoft/terminal/releases/tag/v1.0.1401.0)) with `Ubuntu Mono for Powerline`:
![image](https://user-images.githubusercontent.com/38574447/82376041-61bc4180-99d6-11ea-8186-014cabc7d3c3.png)

The width issue seems to be fixed (with `Cascadia Code PL/Mono PL` too), and the release notes for Terminal seems to indicate it is a rendering issue that they addressed, and imply that other terminal/console apps have to support Unicode 13.0 sizing.

**Closed** 2020-05-19 21:38 UTC
Labels: bug, duplicate
